### ISSUE TITLE
[Silverblue] Crashing on ip autodetect

### ISSUE THREAD

**Issue by vega-d** [casualsnek/cassowary#1]
Hello there, testing on Fedora Silverblue. 
Followed installation instructions in README.md. 

I tried to run `python -m cassowary -a`, in both a podman container and on silverblue itself. Same result. 

When I click Autodetect button on the main menu application crashes and spews this into the terminal:

```vega@fedora-toolbox-35 ~/s/cassowary (main) [SIGABRT]> python -m cassowary -a
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

(process:17098): Gtk-WARNING **: 22:04:35.337: Locale not supported by C library.
	Using the fallback 'C' locale.
Trying to reconnect
setlocale: No such file or directory
Traceback (most recent call last):
  File "/var/home/vega/.local/lib/python3.10/site-packages/cassowary/gui/components/main_ui.py", line 181, in __ip_auto_fill
    ip = ip_by_vm_name(self.inp_vmname.text())
  File "/var/home/vega/.local/lib/python3.10/site-packages/cassowary/base/helper.py", line 25, in ip_by_vm_name
    return out[2].strip().split()[3].split("/")[0]
IndexError: list index out of range
fish: Job 1, 'python -m cassowary -a' terminated by signal SIGABRT (Abort)
```

I am not sure how exactly to troubleshoot this.

**Comment by vega-d** [comment]
update, if I click Autodetect while my VM is not running it doesn't crash but display the correct dialog:

![image](https://user-images.githubusercontent.com/35414314/150422862-df47c310-fe9d-40a5-b837-ce89e41863af.png)

log from the terminal:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

(process:20606): Gtk-WARNING **: 22:09:54.873: Locale not supported by C library.
	Using the fallback 'C' locale.
Trying to reconnect
setlocale: No such file or directory
error: command 'domifaddr' requires <domain> option
setlocale: No such file or directory
error: Failed to query for interfaces addresses
error: Requested operation is not valid: domain is not running
```

**Comment by casualsnek** [comment]
What does ```virsh domifaddr <your vm_name>```  returns when run from terminal ?

**Comment by vega-d** [comment]
> What does `virsh domifaddr <your vm_name>` returns when run from terminal ?

um, nothing? 

```
vega@dart ~> virsh domifaddr win10
 Name       MAC address          Protocol     Address
-------------------------------------------------------------------------------

vega@dart ~> 
```

if I shutdown the vm:
```
vega@dart ~> virsh domifaddr win10
error: Failed to query for interfaces addresses
error: Requested operation is not valid: domain is not running

vega@dart ~ [1]> 
```

**Comment by casualsnek** [comment]
> > What does `virsh domifaddr <your vm_name>` returns when run from terminal ?
> 
> um, nothing?
> 
> ```
> vega@dart ~> virsh domifaddr win10
>  Name       MAC address          Protocol     Address
> -------------------------------------------------------------------------------
> 
> vega@dart ~> 
> ```
> 
> if I shutdown the vm:
> 
> ```
> vega@dart ~> virsh domifaddr win10
> error: Failed to query for interfaces addresses
> error: Requested operation is not valid: domain is not running
> 
> vega@dart ~ [1]> 
> ```

hmm can you do it again, but with sudo while the vm is running ?
Make sure NAT is enabled for the vm and vm has valid I also make sure win10 is the name of vm on virt-manager.

if you get proper output while running with sudo, make sure if have followed the instructions on "Making KVM run without root access" section on README.md and add apparmor rule ! 

If you

**Comment by vega-d** [comment]
> If you get proper output while running with sudo,

welp, I don't XD
![image](https://user-images.githubusercontent.com/35414314/150490059-9cbfe0b8-5013-4ec0-ac9c-a9baee01369c.png)
```
vega@dart ~ [1]> sudo virsh domifaddr win10
error: failed to get domain 'win10'
```

**Comment by casualsnek** [comment]
> > If you get proper output while running with sudo,
> 
> welp, I don't XD ![image](https://user-images.githubusercontent.com/35414314/150490059-9cbfe0b8-5013-4ec0-ac9c-a9baee01369c.png)
> 
> ```
> vega@dart ~ [1]> sudo virsh domifaddr win10
> error: failed to get domain 'win10'
> ```
check if
``` virsh --connect qemu:///session list --all ```

lists your VM.

If this lists the vm i will update the tool to make it work !

**Comment by vega-d** [comment]
> If this lists the vm i will update the tool to make it work !

No luck so far! :D

Same result as if I'm running `virsh domifaddr win10`:
```
vega@dart ~ [1]> virsh --connect qemu:///session list --all
 Id   Name    State
-----------------------
 4    win10   running

vega@dart ~> virsh --connect qemu:///session domifaddr win10
 Name       MAC address          Protocol     Address
-------------------------------------------------------------------------------
```

**Comment by vega-d** [comment]
I tried changing my NIC config in virt-manager, from
`<model type="virtio"/>` to `<model type="e1000e"/>` and back, no changes

```
<interface type="user">
  <mac address="52:54:00:ca:12:65"/>
  <model type="virtio"/>
  <link state="up"/>
  <alias name="net0"/>
  <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
</interface>
```

**Comment by casualsnek** [comment]
https://help.ubuntu.com/community/KVM/Networking

As this article suggests, socket server on vm cannot be accessed from host with usermode networking. I will leave this issue till i manage to create workaround for this issue !

**Comment by vega-d** [comment]
Perhaps for now you can implement an error message so it shows a dialog instead of crashing with a python stacktrace? :D

**Comment by casualsnek** [comment]
> Perhaps for now you can implement an error message so it shows a dialog instead of crashing with a python stacktrace? :D

Sure, next version of linux utility will show an error message instead of crashing !

**Comment by vega-d** [comment]
I think I might've found a workaround. If I create a system session for qemu rather than a user one, I can use NAT networking. The only problem is that now I have to input my password on connecting to qemu session.

![image](https://user-images.githubusercontent.com/35414314/150642663-fffc5349-a1af-40ca-84f3-a507e622fe34.png)

**Comment by casualsnek** [comment]
Can you manage users and group and edit libvirt's config on your system ?

**Comment by vega-d** [comment]
turns out I had a Fedora Silverblue moment. 
if I copy paste lines from `/usr/lib/group` corresponding to `libvirt`, `kvm` and `qemu` groups and paste them to `/etc/group` so it looks like this:
```
vega@dart ~> cat /etc/group
root:x:0:
wheel:x:10:vega
vega:x:1000:
libvirt:x:968:vega
kvm:x:36:vega
qemu:x:107:vega
```
then I can do 
```
sudo usermod -a -G qemu vega
sudo usermod -a -G kvm vega
sudo usermod -a -G libvirt vega
```
and after a reboot `groups` still shows I'm only in `vega wheel` groups but virt manager doesn't ask for sudo password anymore. 
I swear this is not a proper fix but I guess if it works don't touch

**Comment by vega-d** [comment]
I'm closing this issue since this is a distro-specific problem and I found a workaround.

**Comment by juliardi** [comment]
I think I encountered the same problem, and I am using Manjaro. I'll try the workaround to see if it resolves the problem.
