### ISSUE TITLE
how to use with another VM such as virtualbox

### ISSUE THREAD

**Issue by jjgalvez** [casualsnek/cassowary#106]
How can cassoway be used with another vm specifically virtualbox. I understand some features such as auto starting and suspension may not work. I tried to run cassoway with a windows install in virtualbox and after filling out the setup screen I get the following error 

`libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory` 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jjgalvez** [comment]
Please ignore I figured out that I needed to leave the first line in the config blank

**Comment by rxng** [comment]
hi there - I am trying to use another VM (virtualbox) instead of libvirt. when I run python3 -m cassowary it automatically tries to use libvirt. 

I see in the comments to leave a line in the config file blank? how do we do this / where is it located?
