### ISSUE TITLE
Cannot get list of installed apps

### ISSUE THREAD

**Issue by peterlang-p** [casualsnek/cassowary#12]
Hey there :)
this will most likely be in relation to [issue#6](https://github.com/casualsnek/cassowary/issues/6) which was closed, but for me it's still not working. My server is running on a german windows machine.

On my linux machine there are some apps listed, but when clicking on the scan button it does not really do anything:
![Screenshot_20220124_103027](https://user-images.githubusercontent.com/86591121/150756856-513c04cf-eb63-48cc-8c50-79470c02ea33.png)

The log on the windows server mainly shows these two messages:
![Screenshot_20220124_103001](https://user-images.githubusercontent.com/86591121/150756791-ba256cd5-1e00-47d1-95cb-919738db84b1.png)
(Basically it says: "The system cannot find the given file" and "There's no more data available")

Starting applications from commandline like `python3 -m cassowary -c guest-run -- "explorer.exe"` works as expected.

I'm using cassowary v0.2 for server and client.
Thanks for helping me with that :) and let me know, what further information I should provide!

Best regards!

**Comment by casualsnek** [comment]
This is fixed but i have not pushed a released containing the fix !
This is the same bug as previous... Next release will be done on another version bump.. If you need the  compiled windows component i can attach it here, or you can build it yourself !

**Comment by peterlang-p** [comment]
Ah sorry for that. I assumed the v0.2 already had the fix, due to the changelog:
`v0.2 Scanning for app now should work on system with non english locale`
No need to hurry, I'll wait for your "official" release :)

**Comment by casualsnek** [comment]
I just published, a new release can you check if it fixes your issue ?

**Comment by peterlang-p** [comment]
Thanks for that. I'm afraif v0.3 won't start the client for me:

```
Downloads  python3 -m cassowary -a                                                                                                            ✔ 
[ 2022-01-24 13:20:57,874 ] | [  DEBUG ] :  [    __init__ ->                 main  ] -->  Starting configuration GUI 
error: Failed to get option 'domain': Option argument is empty
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lang/.local/lib/python3.9/site-packages/cassowary/__main__.py", line 4, in <module>
    main()
  File "/home/lang/.local/lib/python3.9/site-packages/cassowary/__init__.py", line 154, in main
    mainui = MainWindow()
  File "/home/lang/.local/lib/python3.9/site-packages/cassowary/gui/components/main_ui.py", line 30, in __init__
    self.__reconnect(no_popup=True)
  File "/home/lang/.local/lib/python3.9/site-packages/cassowary/gui/components/main_ui.py", line 151, in __reconnect
    vm_wake()
  File "/home/lang/.local/lib/python3.9/site-packages/cassowary/base/helper.py", line 259, in vm_wake
    vms = subprocess.check_output(["virsh", "domstate", cfgvars.config["vm_name"]])
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['virsh', 'domstate', '']' returned non-zero exit status 1.

```

**Comment by casualsnek** [comment]
i will look into it publish a hotfix asap !

**Comment by peterlang-p** [comment]
Sure thing, here's my `config.json`:
```
{
   "host":"192.168.178.33",
   "winvm_username":"Home",
   "winvm_hostname":"DESKTOP",
   "winvm_password":"{notmypw}",
   "vm_name":"",
   "term":"xterm",
   "rdp_scale":100,
   "rdp_multimon":0,
   "def_icon":"/home/user/Downloads/gui/extrares/defaulticon.png",
   "rdp_flags":"",
   "port":7220,
   "cached_drive_shares":{},
   "winshare_mount_root":"/mnt/casualrdh",
   "eom":"~~!enm!~~",
   "logfile":"/home/user/.config/casualrdh/casualrdh.log",
   "app_session_client":"xfreerdp",
   "full_session_client":"xfreerdp",
   "vm_auto_suspend":0,
   "vm_suspend_delay":600
}
```

**Comment by casualsnek** [comment]
> Sure thing, here's my `config.json`:
> 
> ```
> {
>    "host":"192.168.178.33",
>    "winvm_username":"Home",
>    "winvm_hostname":"DESKTOP",
>    "winvm_password":"{notmypw}",
>    "vm_name":"",
>    "term":"xterm",
>    "rdp_scale":100,
>    "rdp_multimon":0,
>    "def_icon":"/home/user/Downloads/gui/extrares/defaulticon.png",
>    "rdp_flags":"",
>    "port":7220,
>    "cached_drive_shares":{},
>    "winshare_mount_root":"/mnt/casualrdh",
>    "eom":"~~!enm!~~",
>    "logfile":"/home/user/.config/casualrdh/casualrdh.log",
>    "app_session_client":"xfreerdp",
>    "full_session_client":"xfreerdp",
>    "vm_auto_suspend":0,
>    "vm_suspend_delay":600
> }
> ```

Thanks figured out the issue, fixing it.. Also you may remove the def_icon line from config, it will fix icons for windows app while creating shortcuts from GUI !

**Comment by peterlang-p** [comment]
Got it, thanks. I'm running a real win10 pc, since my notebook can't handle a windows vm next to my normal usage :)

**Comment by casualsnek** [comment]
Can you test the attached build of linux client ? If it works i will create a new new release !

**Comment by peterlang-p** [comment]
The installation works now but I can't connect to my windows anymore. Clicking on `Reconnect to server` shows the windows login screen shortly and afterwards this popup appears:
![Screenshot_20220125_091633](https://user-images.githubusercontent.com/86591121/150937983-173fa5a5-af4c-4f10-a707-1096ac0b372e.png)

**Comment by casualsnek** [comment]
Looks like windows server application is not starting properly, can you send the windows logs !

**Comment by peterlang-p** [comment]
Starting an application via commandline works, though. It's just the gui application that seems not to be able to establish the connection. I'll get the windows logs and edit them here in a minute.

**Comment by casualsnek** [comment]
> Starting an application via commandline works, though. It's just the gui application that seems not to be able to establish the connection. I'll get the windows logs and edit them here in a minute.

When starting the app, windows server application is not used so it is working, can you check if opening GUI while an application launched from commandline is active corrects the connection issue !

**Comment by peterlang-p** [comment]
Trying to start the gui with an windows application already running via commandline closes the application and prompts the upper timeout message.

**Comment by casualsnek** [comment]
> Trying to start the gui with an windows application already running via commandline closes the application and prompts the upper timeout message.

Maybe the cassowary server application is not running on windows ? Can you open task manager "taskmgr.exe" and check if cassowary process is active ?

**Comment by casualsnek** [comment]
Are you using laptop with windows installation? i just found out that created scheduled task don't run on laptops unless plugged in while !

**Comment by casualsnek** [comment]
I am closing this issue since there was no further response for a long time, the scheduled task not running on laptops is fixed now. If you encounter any other issue, feel free to open another issue !
