### ISSUE TITLE
Unable to open cassowary configuration utility.

### ISSUE THREAD

**Issue by 102660** [casualsnek/cassowary#142]
**Describe the bug**
When I attempt to run `python3 -m cassowary -a`, I get the error `/usr/bin/python3: No module named cassowary.__main__; 'cassowary' is a package and cannot be directly executed`

**To Reproduce**
1. Install cassowary as usual using the instructions in the README
2. Run `python3 -m cassowary -a`

**Expected behavior**
It should open the configuration utility according to [this](https://github.com/casualsnek/cassowary/blob/main/docs/2-cassowary-install.md).

**Screenshots**
[image](https://github.com/casualsnek/cassowary/assets/126220826/9b35b88e-e2e2-4af5-9412-03a46aee103d)

**System information:**
 - Cassowary Linux client version: unable to find due to the error, most likely 0.6
 - Cassowary windows component version: 0.6
 - Linux Distribution: Fedora 39
 - Windows/Edition used: Windows 10 Pro

**Comment by casualsnek** [comment]
You installed wrong cassowary, uninstall it and install this cassowary using the provided wheel instead of using ``pip install cassowary``

**Comment by 102660** [comment]
Thanks for the help!
