### ISSUE TITLE
Error with open apps

### ISSUE THREAD

**Issue by namdeptrai2003** [casualsnek/cassowary#143]
**Describe the bug**
Can't open any apps. No windows appear.
**To Reproduce**
1. Go to Terminal 
2. Type: python3 -m cassowary -c guest-run -- 'C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE' %u
3. See error

**Expected behavior**
[dimacat@dimacat-precision7510 ~]$ python3 -m cassowary -c guest-run -- 'C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE' %u
[ 2024-01-19 07:45:58,455 ] | [  DEBUG ] :  [      helper ->              vm_wake  ] -->  Attempting to resume VM 
[ 2024-01-19 07:45:58,466 ] | [ WARNING ] :  [      helper ->              vm_wake  ] -->  VM state is not set to suspended : State -> '1'  
[ 2024-01-19 07:45:58,467 ] | [  DEBUG ] :  [      helper ->     fix_black_window  ] -->  Opening & closing a test window to trigger login or try to fix black screen bug on first launch 
[ 2024-01-19 07:45:58,467 ] | [  DEBUG ] :  [      helper ->     fix_black_window  ] -->  Trying to fix black window bug by opening a test window before requested application - 1705625158.4677012CMDLINE: xfreerdp /d:"RDPWINDOWS" /u:"Administrator" /p:"" /v:"192.168.122.11" +clipboard /a:drive,root,/ +decorations /cert-ignore /sound /scale:100 /dynamic-resolution /span  /wm-class:"cassowaryApp-echo" /app:"ipconfig.exe" 
[ 2024-01-19 07:45:59,130 ] | [  DEBUG ] :  [      helper ->     fix_black_window  ] -->  Test window opened and closed ! 
[ 2024-01-19 07:45:59,130 ] | [  DEBUG ] :  [      helper ->     fix_black_window  ] -->  An app was already opened, the black window should not appear now ! 
[ 2024-01-19 07:45:59,131 ] | [  DEBUG ] :  [    __init__ ->                 main  ] -->  guest-run with commandline: xfreerdp /d:"RDPWINDOWS" /u:"Administrator" /p:"" /v:192.168.122.11 +clipboard /a:drive,root,/ +decorations /cert-ignore /sound /scale:100 /dynamic-resolution /span  /wm-class:"cassowaryApp-EXCEL.EXE" /app:"C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE" /app-icon:"/home/dimacat/.local/lib/python3.11/site-packages/cassowary/base/../gui/extrares/cassowary_app.png" /app-cmd:"%u " 
[07:45:59:377] [3069:3070] [WARN][com.freerdp.core.nla] - SPNEGO received NTSTATUS: STATUS_ACCOUNT_RESTRICTION [0xC000006E] from server
[07:45:59:377] [3069:3070] [ERROR][com.freerdp.core] - nla_recv_pdu:freerdp_set_last_error_ex ERRCONNECT_ACCOUNT_RESTRICTION [0x00020017]
[07:45:59:377] [3069:3070] [ERROR][com.freerdp.core.rdp] - rdp_recv_callback: CONNECTION_STATE_NLA - nla_recv_pdu() fail
[07:45:59:377] [3069:3070] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1

**Screenshots**
![Screenshot_20240119_074930](https://github.com/casualsnek/cassowary/assets/24204127/01f67d7d-c215-43a7-9e7d-756b0502184b)

**System information:**
 - Cassowary 0.6
 - Linux Distribution: EndeavourOS with Plasma KDE
 - Windows/Edition used: Windows 11 Lite from here: https://github.com/WhatTheBlock/WindowsSimplify

**Comment by casualsnek** [comment]
Can you launch a full RDP session using cassowary ?

**Comment by namdeptrai2003** [comment]
Hi @casualsnek , I can't do it. Here is the logs and screenshot: 
[ 2024-01-20 07:45:18,187 ] | [ WARNING ] :  [     main_ui -> populate_applications  ] -->  Looks like some app returned data that cannot be parsed : [None, 'C:\\Program Files\\WindowsApps\\Microsoft.Paint_11.2201.22.0_x64__8wekyb3d8bbwe\\PaintApp\\mspaint.exe', None] : Traceback (most recent call last):
  File "/home/dimacat/.local/lib/python3.11/site-packages/cassowary/gui/components/main_ui.py", line 350, in populate_applications
    name = app[0].split(":")[0]
           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
 
[ 2024-01-20 07:45:18,187 ] | [ WARNING ] :  [     main_ui -> populate_applications  ] -->  Looks like some app returned data that cannot be parsed : [None, 'C:\\Program Files\\WindowsApps\\Microsoft.WindowsNotepad_11.2112.32.0_x64__8wekyb3d8bbwe\\Notepad\\Notepad.exe', None] : Traceback (most recent call last):
  File "/home/dimacat/.local/lib/python3.11/site-packages/cassowary/gui/components/main_ui.py", line 350, in populate_applications
    name = app[0].split(":")[0]
           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
 
[ 2024-01-20 07:45:18,188 ] | [ WARNING ] :  [     main_ui -> populate_applications  ] -->  Looks like some app returned data that cannot be parsed : [None, 'C:\\Program Files\\WindowsApps\\Microsoft.DesktopAppInstaller_1.17.10691.0_x64__8wekyb3d8bbwe\\winget.exe', None] : Traceback (most recent call last):
  File "/home/dimacat/.local/lib/python3.11/site-packages/cassowary/gui/components/main_ui.py", line 350, in populate_applications
    name = app[0].split(":")[0]
           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
 
[ 2024-01-20 07:45:18,201 ] | [  DEBUG ] :  [      client ->               __send  ] -->  Sending message to server 
[ 2024-01-20 07:45:19,320 ] | [  DEBUG ] :  [      client ->               __send  ] -->  Sending message to server 
[ 2024-01-20 07:45:23,256 ] | [  DEBUG ] :  [      helper ->             full_rdp  ] -->  Creating a full RDP session with commandline  : {rdc} /d:"{domain}" /u:"{user}" /p:"{passd}" /v:{ip} /a:drive,root,{share_root} +auto-reconnect +clipboard /cert-ignore /audio-mode:1 /scale:{scale} /wm-class:"cassowaryApp-FULLSESSION" /dynamic-resolution /{mflag} {rdflag} 1> /dev/null 2>&1 & 
[ 2024-01-20 07:45:23,269 ] | [  DEBUG ] :  [      helper ->             full_rdp  ] -->  Full RDP session ended ! 
[ 2024-01-20 07:45:28,602 ] | [  DEBUG ] :  [      helper ->             full_rdp  ] -->  Creating a full RDP session with commandline  : {rdc} /d:"{domain}" /u:"{user}" /p:"{passd}" /v:{ip} /a:drive,root,{share_root} +auto-reconnect +clipboard /cert-ignore /audio-mode:1 /scale:{scale} /wm-class:"cassowaryApp-FULLSESSION" /dynamic-resolution /{mflag} {rdflag} 1> /dev/null 2>&1 & 
[ 2024-01-20 07:45:28,607 ] | [  DEBUG ] :  [      helper ->             full_rdp  ] -->  Full RDP session ended ! 
[ 2024-01-20 07:45:29,556 ] | [  DEBUG ] :  [      helper ->             full_rdp  ] -->  Creating a full RDP session with commandline  : {rdc} /d:"{domain}" /u:"{user}" /p:"{passd}" /v:{ip} /a:drive,root,{share_root} +auto-reconnect +clipboard /cert-ignore /audio-mode:1 /scale:{scale} /wm-class:"cassowaryApp-FULLSESSION" /dynamic-resolution /{mflag} {rdflag} 1> /dev/null 2>&1 & 
[ 2024-01-20 07:45:29,570 ] | [  DEBUG ] :  [      helper ->             full_rdp  ] -->  Full RDP session ended ! 
[ 2024-01-20 07:45:30,216 ] | [  DEBUG ] :  [      helper ->             full_rdp  ] -->  Creating a full RDP session with commandline  : {rdc} /d:"{domain}" /u:"{user}" /p:"{passd}" /v:{ip} /a:drive,root,{share_root} +auto-reconnect +clipboard /cert-ignore /audio-mode:1 /scale:{scale} /wm-class:"cassowaryApp-FULLSESSION" /dynamic-resolution /{mflag} {rdflag} 1> /dev/null 2>&1 & 
[ 2024-01-20 07:45:30,230 ] | [  DEBUG ] :  [      helper ->             full_rdp  ] -->  Full RDP session ended ! 
[ 2024-01-20 07:45:30,628 ] | [  DEBUG ] :  [      helper ->             full_rdp  ] -->  Creating a full RDP session with commandline  : {rdc} /d:"{domain}" /u:"{user}" /p:"{passd}" /v:{ip} /a:drive,root,{share_root} +auto-reconnect +clipboard /cert-ignore /audio-mode:1 /scale:{scale} /wm-class:"cassowaryApp-FULLSESSION" /dynamic-resolution /{mflag} {rdflag} 1> /dev/null 2>&1 & 
[ 2024-01-20 07:45:30,632 ] | [  DEBUG ] :  [      helper ->             full_rdp  ] -->  Full RDP session ended ! 
[ 2024-01-20 07:45:38,698 ] | [  DEBUG ] :  [      helper ->             full_rdp  ] -->  Creating a full RDP session with commandline  : {rdc} /d:"{domain}" /u:"{user}" /p:"{passd}" /v:{ip} /a:drive,root,{share_root} +auto-reconnect +clipboard /cert-ignore /audio-mode:1 /scale:{scale} /wm-class:"cassowaryApp-FULLSESSION" /dynamic-resolution /{mflag} {rdflag} 1> /dev/null 2>&1 & 
[ 2024-01-20 07:45:38,712 ] | [  DEBUG ] :  [      helper ->             full_rdp  ] -->  Full RDP session ended ! 
![Uploading Screenshot_20240120_074542.png…]()

**Comment by Dimacat-exe** [comment]
Help?

**Comment by Dimacat-exe** [comment]
@casualsnek fixed it but after open 1 app and close it, i cant open the next app. Is there any workaround?

**Comment by phildong** [comment]
> @casualsnek fixed it but after open 1 app and close it, i cant open the next app. Is there any workaround?

Could you share how you fixed it?

**Comment by iopanio** [comment]
Install xfreerdp. For Arch, it's pacman -S freerdp2. pacman -S xfreerdp will install xfreerdp3, which is incompatible.

**Comment by Dimacat-exe** [comment]
As I fixed it, i will close it. Hope other can find a solution

**Comment by namdeptrai2003** [comment]
As I fixed it, i will close it. Hope other can find a solution
