### ISSUE TITLE
[Feature Request]  Notification when vm is suspended

### ISSUE THREAD

**Issue by hwak722** [casualsnek/cassowary#20]
Can you add option to enable notification when the vm is put to sleep, it wil be easier to know if the vm is suspended wthout checking virt manager

**Comment by casualsnek** [comment]
New version will be out today that will have this option added :)

**Comment by casualsnek** [comment]
I just made a release that should have this feature, can you check it out ?

**Comment by hwak722** [comment]
Yes, the notifications work.

Another issue is that config is not updated in background if vm auto suspend setting is changed because tc variable ( https://github.com/casualsnek/cassowary/blob/main/app-linux/src/cassowary/base/helper.py#L236 ) is never incremented and never reach 10

**Comment by casualsnek** [comment]
> Yes, the notifications work.
> 
> Another issue is that config is not updated in background if vm auto suspend setting is changed because tc variable ( https://github.com/casualsnek/cassowary/blob/main/app-linux/src/cassowary/base/helper.py#L236 ) is never incremented and never reach 10

Config will be updated now. I have pushed the changes and updated the release files too !
