### ISSUE TITLE
Xcopy issue in setup.bat

### ISSUE THREAD

**Issue by san-kumar** [casualsnek/cassowary#22]
I was unable to run `setup.bat` on windows because it has the following command in it

```
Xcopy /E /I /Y cassowary\ "C:\Program Files\cassowary\"
```

This showed an invalid path error.

I think the trailing slash is making it fail because removing it fixed the error

````
Xcopy /E /I /Y cassowary "C:\Program Files\cassowary\"
````

Not sure if it's just my Win10 setup but something I wanted to bring to your attention

**Comment by casualsnek** [comment]
Thanks, i will check if it works as expected !

**Comment by casualsnek** [comment]
Thanks for reporting the issue.
It seems to work on some system while fail on other. I will push changes with trailing slashes removed which seems to work on most cases !
