### ISSUE TITLE
Possible typo in install script

### ISSUE THREAD

**Issue by yllekz** [casualsnek/cassowary#26]
```
$ git clone https://github.com/casualsnek/cassowary
$ cd cassowary
$ ./buildall.sh
```

I needed to run ``chmod +x buildall.sh`` which allowed buildall.sh to be executable, but upon running it, I get the following error in Linux Mint Cinnamon:

```
==> Building linux component
/usr/bin/python3: No module named build
==> Done
==> Building windows component
./buildall.sh: line 9: ./build.sh: Permission denied
==> Done
```

Is this a typo? Should it be ``buildall.sh`` again?

**Comment by yllekz** [comment]
I was able to get past this by running:

 ```
cd app-linux/
chmod +x build.sh
cd ..
cd app-win/
chmod +x build.sh
./buildall.sh
```

Which progresses farther.

**Comment by casualsnek** [comment]
Thank you for reporting the issue, i will add option to skip checksum verification and apply proper attributes to build scripts !
