### ISSUE TITLE
RemoteApps for Linux - maybe a way to simplify RemoteApp configuration

### ISSUE THREAD

**Issue by bmullan** [casualsnek/cassowary#28]
Hi,  I've been using Kim Knight's RemoteAppTool since about 2013 to run Windows RemoteApps on my Ubuntu Linux machines.
[Although my WordPress blog about configuring it](https://bmullan.wordpress.com/2012/09/17/howto-integrate-windows-apps-into-the-ubuntu-linux-desktop-using-windows-remoteapp/) has not been updated in a couple years I still use the general config concept today with Ubuntu 20.04.

I'm creating this "issue" not as a problem but to mention something I learned back then about Windows.
If I configure the only RemoteApp to be "Windows Explorer" it turns out that Windows Eplorer can be used as a Launcher for any other Windows App I want to use from Linux any "other' Windows App I launch that way "Inherits" the "RemoteApp" functions/capabilities of Explorer and when launched appear in their own Linux "window" which can be moved/resized/minimized etc.

On the Windows VM I created a folder called "WinApps" and placed "shortcuts" to all the Windows Applications I wanted to run on Linux into that WinApps Folder

My xFreeRDP command line to do this looks like this:

xfreerdp /cert-ignore /u:UserID /p:Passwd /drive:shared-folder,/home/UserID/shared-folder +clipboard /sound:sys:alsa /app:'%windir%\explorer.exe' /v:IP_of_Win-VM

When Explorer appears on my Linux Desktop I use it to change to my Windows "WinApps" Directory and click on any Application I want to run.

Benefit:  
There was only 1 RemoteApp to configure.

Maybe this method will work with Cassowary also?

**Comment by casualsnek** [comment]
On cassowary we do not publish applications as remoteapp, by setting     "fAllowUnlistedRemotePrograms"=dword:00000001 in registry we can run any application as remoteapp, 

Whenever app is launched with ```cassowary -c guest-run -- app.exe``` it just replaces explorer.exe on similar xfreerdp command as yours with the specified application.

In short we never configure remoteapps, we modify registry to allow any application to run as remoteapp and just launch it ! :)

**Comment by casualsnek** [comment]
If you think your question was not answered properly or have any other issue/questions feel free to open anothwr isaue !
