### ISSUE TITLE
Attempting to set 'exe' as a 'Launch on host' association will break the Windows install

### ISSUE THREAD

**Issue by owendaprile** [casualsnek/cassowary#30]
I was stupid and didn't read carefully and thought this would work the other way around (allow me to launch exes from Linux in the VM), but unsurprisingly it doesn't work. It's not too hard to fix, but either the GUI or the server should stop you from registering a .exe (and probably .msi too).

**Comment by casualsnek** [comment]
Thanks for informing, i will add a filter for those file types in server application !

**Comment by casualsnek** [comment]
https://github.com/casualsnek/cassowary/commit/18a68ebabcbc8375c54031f8cd6c152469b0ae2c After this commit, an error will be returned by server when setting exe and msi files to launch on host !

**Comment by owendaprile** [comment]
Thanks for the fast turnaround! Excited to see this project progress.
