### ISSUE TITLE
[ Documentation ] Mention that it can be used with windows 7 too

### ISSUE THREAD

**Issue by hwak722** [casualsnek/cassowary#32]
Setup guide says windows 10 is required, but it also works perfectly with windows 7. In my opinion Windows 7 will be better for people who want to use office or some other applications that work in windows 7 as it is less resource hungry (2gb ram and 2 cores work perfectly ) .

Without mention on windows 7 on install guide people will only use windows 10 which takes more resource and come across UWP apps which are extremely buggy.

**Comment by casualsnek** [comment]
Thank you, i will update install instruction for windows 7

**Comment by casualsnek** [comment]
It has now been mentioned after leoxff's pr !
