### ISSUE TITLE
Request failed mapping linux to windows

### ISSUE THREAD

**Issue by rxng** [casualsnek/cassowary#34]
Mounting the Documents folder in /home/user/Documents to \\tsclient\root\home\rxng\Documents , on drive letter F

results in the following error:

![image](https://user-images.githubusercontent.com/19649766/152878324-5f778cf5-eed2-4ee9-b963-8a6f6d2f5baf.png)

**Comment by casualsnek** [comment]
Duplicate of : https://github.com/casualsnek/cassowary/issues/11
I recommend continuing discussion on that thread will be better.

By the way can you run ``` python3 -m cassowary -c guest-run -- cmd.exe ``` and then run ``` net use * /delete ``` as suggested in older thread,  reboot the VM and see if this error occurs again !

**Comment by casualsnek** [comment]
I am closing this thread, you may continue discussion in the older thread !
