### ISSUE TITLE
No 3D acceleration in VM

### ISSUE THREAD

**Issue by chqoot-vgxu** [casualsnek/cassowary#4]
Not really an issue, but the readme says to use virtio video driver with 3D acceleration enabled, unfortunately the windows driver for it is display only meaning it doesn't have any acceleration, not even 2D. So it might even have worse performance than QXL.

**Comment by casualsnek** [comment]
Maybe, i do not use much graphically intensive applications while testing, bt the way one can use other hypervisors like VmWare Which provides far better 3d performance for non GPU passthrough setups !

**Comment by casualsnek** [comment]
Updated the VM setup setup guide with small note on bottom suggesting other virtualization platform for better performance !
