### ISSUE TITLE
A number of problems when working with tiling WM.

### ISSUE THREAD

**Issue by MuratovAS** [casualsnek/cassowary#40]
good day
I use `Sway WM`. I observe some problems in the operation of the application in my WM.
I understand that my problems are very specific. But maybe someday they can be fixed) 

1) A number of problems when working with floating windows (not all)
When Windows creates an auxiliary window, `casualsnek` passes it to host and my VM creates a window with the `floating` parameter. Everything seems to be in order. But my WM tries to adjust the size of this window, so does `casualsnek`. As a result, the window is reduced to the limit.
I think this can be solved by forwarding to `Windows` information about the size of the window only after changing it. 
![recording-2022-02-09-223531](https://user-images.githubusercontent.com/50487552/153258272-3350e652-afc2-474f-90da-b10aa65ad7c1.gif)

2) Inaccurate positioning of the picture in the window.
After starting the window visually, the window occupies all the allotted space. But the cursor on `Windows` is not the same as the cursor on `Host`. I've found a way to minimize this by simply flipping the window (minimize, maximize). But this does not completely solve the problem, and black frames appear around the edges. (you can see them in point 1) 
![recording-2022-02-09-224509](https://user-images.githubusercontent.com/50487552/153259821-13b8449a-cb3e-459b-a00c-68858720be7d.gif)

P.S. Thanks, your project makes my life easier today :)

**Comment by casualsnek** [comment]
Thank you for reporting. These issue look like issue on freerdp itself. The issues related to rendering are better suited at https://github.com/FreeRDP/FreeRDP/issues . If you plan to report issue to freerdp run the application from commandline, it should output used xfreerdp commandline and the output from xfreerdp.

**Comment by MuratovAS** [comment]
Thank you. I understood you.
Running in `floating` makes things worse. In such a case, the parent window is waiting for the same problem.
