### ISSUE TITLE
Appplication disappears for short time when new application is launched

### ISSUE THREAD

**Issue by hwak722** [casualsnek/cassowary#45]
When i am working on Microsoft word and then open excel then word window disappears and then both window reappear making it look like it crashed or something. I tested with freerdp command line too and even though it looks like expected behavior from freerdp i would love if you can find a way to open new application without running applications disappearing for short time !

It gets annoying when you more than one windows application running on particular workspace, open another window and all the previous windows get to active workspace cluttering everything !

**Comment by casualsnek** [comment]
Thank you for feedback, it should be pretty simple to implement since we have a server application which can open applications instead. Expect this feature in 0.6 release that i will push after few hours or a day !

**Comment by casualsnek** [comment]
Just pushed v0.6 can you see if this issue is fixed on this release !
