### ISSUE TITLE
Windows 10 no internet access

### ISSUE THREAD

**Issue by xerohackcom** [casualsnek/cassowary#51]
I've followed your guide on setting up Windows 10 virtual machine using virt-manager and virtio. Every instruction was followed and the virtual machine runs smooth, but does not have internet access. I tried multiple times but the same results. Any solutions?

**Comment by xerohackcom** [comment]
**Anyone facing this issue - I found my problem!**: After trying everything on the internet, I found the damn problem!! Running a VPN on host system messed up the ip leasing to the guest VM.. As soon as I shutdown the VPN on host system, my guest VM's got internet access.

Just something to note in the future..

**Comment by casualsnek** [comment]
> **Anyone facing this issue - I found my problem!**: After trying everything on the internet, I found the damn problem!! Running a VPN on host system messed up the ip leasing to the guest VM.. As soon as I shutdown the VPN on host system, my guest VM's got internet access.
> 
> Just something to note in the future.. 

Thank you for your findings, i will address this issue in FAQ section !
