### ISSUE TITLE
Constant requests for sudo password

### ISSUE THREAD

**Issue by juandpineiro** [casualsnek/cassowary#55]
**Describe the bug**
When using the host client in full RDP mode or single app mode, the requests for sudo password are constant, sometimes even several requests at the same time.

**To Reproduce**
1. Run `cassowary -f` and use guest for a couple of minutes, or run in single-app mode and use for a couple of minutes. Password request reads "System policy prevents management of local virtualized systems" This is the same message displayed when opening `virt-manger` or running `cassowary -f` or single-app mode for the first time.
2. The requests persist even after closing the RDP session or closing the single app. The auto-suspend feature is disabled.

**Expected behavior**
Maybe only an initial request when going into full RDP mode or single-app mode?

**System information:**
 - Cassowary Linux client version: 0.6A
 - Cassowary windows component version: 0.6A
 - Linux Distribution: Fedora 35 Silverblue (immutable)
 - Windows/Edition used: Windows 10

EDIT:
As mentioned in [#1](https://github.com/casualsnek/cassowary/issues/1#issue-1109766852) I added my user to the `libvirt` `kvm` and `qemu` groups to see if the behavior improves.

**Comment by casualsnek** [comment]
Looks like the usergroup issue to me, and i don't know much about how silverblue handles groups !

If you are not using using autosuspend you can leave VM name blank and save changes which will prevent cassowary from using libvirt. If is is issue with groups i will check if i can get it working and update readme but this may take some time !

**Comment by juandpineiro** [comment]
Ok this was dumb. I followed the same procedure as in #1 but I had a typo in my `/etc/group` file. Now it's working fine and `virt-manager` and when using `cassowary` it won't ask for a password. Thanks! Closing
