### ISSUE TITLE
Windows apps not launching

### ISSUE THREAD

**Issue by artav4** [casualsnek/cassowary#69]
**Describe the bug**
Hi guys, I have recently installed Cassowary 0.6 through pip on my Arch Linux with Windows 10, but I've noticed that whatever the program that I was trying to launch throught it, it never worked. So I decided to try to launch it within the terminal and here is the full output of what it gave me (here Excel):

$ python3 -m cassowary -c guest-run -- 'C:\\Program Files\\Microsoft Office\\Root\\Office16\\EXCEL.EXE' %u
[ 2022-03-28 22:24:15,967 ] | [  DEBUG ] :  [      helper ->              vm_wake  ] -->  Attempting to resume VM 
[ 2022-03-28 22:24:15,973 ] | [ WARNING ] :  [      helper ->              vm_wake  ] -->  VM state is not set to suspended : State -> '1'  
[ 2022-03-28 22:24:15,973 ] | [  DEBUG ] :  [      helper ->     fix_black_window  ] -->  Opening & closing a test window to trigger login or try to fix black screen bug on first launch 
[ 2022-03-28 22:24:15,973 ] | [  DEBUG ] :  [      helper ->     fix_black_window  ] -->  Trying to fix black window bug by opening a test window before requested application - 1648499055.9737747CMDLINE: xfreerdp /d:"DESKTOP-IQGQMPU" /u:"arthur" /p:"2405" /v:"192.168.122.99" +clipboard /a:drive,root,/ +decorations /cert-ignore /sound /scale:100 /dynamic-resolution /span  /wm-class:"cassowaryApp-echo" /app:"ipconfig.exe" 
[ 2022-03-28 22:24:16,534 ] | [  DEBUG ] :  [      helper ->     fix_black_window  ] -->  Test window opened and closed ! 
[ 2022-03-28 22:24:16,534 ] | [  DEBUG ] :  [      helper ->     fix_black_window  ] -->  An app was already opened, the black window should not appear now ! 
[ 2022-03-28 22:24:16,535 ] | [  DEBUG ] :  [    __init__ ->                 main  ] -->  guest-run with commandline: xfreerdp /d:"DESKTOP-IQGQMPU" /u:"arthur" /p:"2405" /v:192.168.122.99 +clipboard /a:drive,root,/ +decorations /cert-ignore /sound /scale:100 /dynamic-resolution /span  /wm-class:"cassowaryApp-EXCEL.EXE" /app:"C:\\Program Files\\Microsoft Office\\Root\\Office16\\EXCEL.EXE" /app-icon:"/usr/lib/python3.10/site-packages/cassowary/base/../gui/extrares/cassowary_app.png" /app-cmd:"%u " 
[22:24:17:937] [3880:3881] [WARN][com.freerdp.core.nla] - SPNEGO received NTSTATUS: STATUS_LOGON_FAILURE [0xC000006D] from server
[22:24:17:937] [3880:3881] [ERROR][com.freerdp.core] - nla_recv_pdu:freerdp_set_last_error_ex ERRCONNECT_LOGON_FAILURE [0x00020014]
[22:24:17:937] [3880:3881] [ERROR][com.freerdp.core.rdp] - rdp_recv_callback: CONNECTION_STATE_NLA - nla_recv_pdu() fail
[22:24:17:937] [3880:3881] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1

Can anyone help me understand to what are the errors related and how to resolve it? I can provide extra infos if needed.

**Comment by casualsnek** [comment]
It looks like you are using windows login PIN as password. PIN does not work, you have to use windows password instead, for it to work !

> 

It looks like you are using windows login PIN as password. PIN does not work, you have to use windows password instead, for it to work !

**Comment by artav4** [comment]
Thank you, it was exactly that, now everything is working great!
