### ISSUE TITLE
Cannot start Cassowary linux

### ISSUE THREAD

**Issue by hwak722** [casualsnek/cassowary#7]
if i start my vm and try to run cassowary GUI tool, it says connection failed !
But once i run any other app through cassowary created shortcut, The GUI also starts working as expected..

Is  this behavior expected or is it a bug ? 
It is inconvenient to use GUI at this state and will confuse a lot of people

**Comment by casualsnek** [comment]
This is expeccted behaviour in current version, I will update next version of tool to fix this problem :)

**Comment by casualsnek** [comment]
Can you check if this issue is solved ! I just made a new release !

**Comment by hwak722** [comment]
it is working after update
