### ISSUE TITLE
Notification Sound From Windows App

### ISSUE THREAD

**Issue by rammjet** [casualsnek/cassowary#81]
I'm running eM Client on Windows 10 as my preferred email client.  I'm wondering whether the notification sound that is made for newly received mail can be transmitted to Linux (Mint 20.3)?  I seem to hear the Windows notifications (sometimes).  But the little wav file that is supposed to be played when there is new mail is not passed through.

Just as a note from installation of Cassowary:  the `wget https://gitlab.com/apparmor/apparmor/-/blob/master/profiles/apparmor.d/usr.sbin.dnsmasq -O ~/usr.sbin.dnsmasq` downloads the html of the page for me.  Had to go get the file manually.

**Comment by casualsnek** [comment]
Full support for notifcation passthrough would be done when this gets completed: https://github.com/casualsnek/cassowary/issues/70

For the issue with ```usr.sbin.dnsmasq``` i will update the readme with proper url !

**Comment by rammjet** [comment]
Thanks.
