### ISSUE TITLE
GTA V

### ISSUE THREAD

**Issue by capriciousduck** [casualsnek/cassowary#83]
Is it possible to play GTA 5 using cassowary?

**Comment by foxyllakora** [comment]
It might, but there would be little to no 3D hardware acceleration, so even if it does run the performance would not be great. Wine/Proton is gonna be your best option for that

**Comment by casualsnek** [comment]
> Is it possible to play GTA 5 using cassowary?

It might be possible while using a VM with GPU passthrough, but i am sure it wont be a good experience playing games through cassowary !
