### ISSUE TITLE
Use alternative RDP client

### ISSUE THREAD

**Issue by raffaem** [casualsnek/cassowary#84]
**Is your feature request related to a problem? Please describe.**

My Windows 11 Home Edition does not support RDP.

Is it possible to use an alternative RDP client rather than the Windows integrated one?

**Describe the solution you'd like**

use an alternative RDP client rather than the Windows integrated one

**Describe alternatives you've considered**

Maybe [FreeRDP](https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds)?

**Comment by arimgibson** [comment]
@raffaem are you connecting to a Windows PC you already have, or is it a VM in Linux? Fun fact is that you don't need a license key for Windows; you should install the Windows VM as Windows 10 Pro even though you don't have a license key. As far as I remember, some of the tools used for the VM setup might not support Windows 11? But I could be wrong there

**Comment by casualsnek** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> My Windows 11 Home Edition does not support RDP.
> 
> Is it possible to use an alternative RDP client rather than the Windows integrated one?
> 
> **Describe the solution you'd like**
> 
> use an alternative RDP client rather than the Windows integrated one
> 
> **Describe alternatives you've considered**
> 
> Maybe [FreeRDP](https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds)?

On linux side we already use freerdp and rdp client, but i am not sure if freerdp server exists for windows so we use what already exists in windows !

**Comment by raffaem** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > My Windows 11 Home Edition does not support RDP.
> > Is it possible to use an alternative RDP client rather than the Windows integrated one?
> > **Describe the solution you'd like**
> > use an alternative RDP client rather than the Windows integrated one
> > **Describe alternatives you've considered**
> > Maybe [FreeRDP](https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds)?
> 
> On linux side we already use freerdp and rdp client, but i am not sure if freerdp server exists for windows so we use what already exists in windows !

No looks like it's only a server.

Anyway Windows 11 Education works fine as well (it has RDP).
