### ISSUE TITLE
virtqemud-sock doesn't exist after attempting to retrieve IP

### ISSUE THREAD

**Issue by DaKingof** [casualsnek/cassowary#85]
**Describe the bug**
I installed the app from the AUR and all packages. I opened the app from the command line to the GUI. As soon as I got to the part where I input the VM Domain name and Autodetect IP the GUI crashed and now I am getting this error pictured below. I also am not able to connect to QEMU/KVM connection anymore. Only the user session is availible now. I check the file location and it is indeed not there. Also, I did install the windows script on my Windows 11 host before attempting to run cassowary from my terminal window.

![image](https://user-images.githubusercontent.com/31186364/174202763-686743e7-f30b-4ce1-940e-a350a00a6f47.png)

**Comment by casualsnek** [comment]
Can you provide some more details on your system, version of libvirt/vert-manager and your operating system ?

**Comment by DaKingof** [comment]
Virt-Manager version 4.0.0
Libvirt version 1:8.4.0-1
![image](https://user-images.githubusercontent.com/31186364/174517693-604f784a-5493-4655-bc55-b91937d0160d.png)

**Comment by DaKingof** [comment]
Fixed by running: sudo systemctl enable libvirtd.service then sudo systemctl start libvirtd.service
