### ISSUE TITLE
How do I install libvirt-python3 on debian/ubuntu (Pop!_OS)

### ISSUE THREAD

**Issue by wondercomm** [casualsnek/cassowary#86]
Hi There! 

I'm using Pop!_OS, I'm stuck on Step 2, install cassowary on linux (host). 

```
sudo apt install python3 python3-pip freerdp libvirt-python
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package freerdp is a virtual package provided by:
  freerdp2-x11 2.6.1+dfsg1-3ubuntu2.1
  freerdp2-shadow-x11 2.6.1+dfsg1-3ubuntu2.1
You should explicitly select one to install.
```
```

E: Package 'freerdp' has no installation candidate
E: Unable to locate package libvirt-python
```

So, I did some search and was able to find freeRDP package here: https://github.com/conankiz/Ubuntu-20.04/blob/main/Install%20freerdp%20on%20Ubuntu%2020.04.md#step1
Ran the following command:

`sudo apt install freerdp2-x11`

and it worked.

Where can I find the **libvirt-python3** package, so I can continue with the install? 

Also, Will you be releasing instructions for ubuntu/pop os at any point in time?

**Comment by saivishnu725** [comment]
`python3-libvirt` is the program name in Ubuntu.
[Link for the package.](https://packages.ubuntu.com/bionic/python3-libvirt)

**Comment by wondercomm** [comment]
Thank you. :)
