### ISSUE TITLE
Unable to share a folder from linux host to windows

### ISSUE THREAD

**Issue by ThreeVeil939527** [casualsnek/cassowary#94]
**Describe the bug**
When trying to share a folder it errors and says request failed

**To Reproduce**
Install according to the docs and use the gui to share a folder from linux to windows.

**Expected behavior**
A shared folder with the drive letter D:/

**Screenshots**
![image](https://user-images.githubusercontent.com/76134402/180515874-05aa76bd-2cfe-498d-bb50-427b0a14cb05.png)

**System information:**
 - Host version: 0.6A
 - Client version 0.6A
 - Linux Distribution: Arch Linux
 - Windows/Edition: 10/pro

**Comment by sleeyax** [comment]
@Chez123321 how did you solve this? I'm having the same issue.

**Comment by casualsnek** [comment]
> @Chez123321 how did you solve this? I'm having the same issue.

Can you try while you have at least one windows application open ? If the VM has just booted up and no application has opened, the user logon is not done so mapping cannot be done at that moment !

**Comment by sleeyax** [comment]
I have successfully connected to the VM and started cmd via `cassowary -c guest-run -- cmd.exe`. But the mapping still fails with another obscure error now:

<img width="675" alt="image" src="https://user-images.githubusercontent.com/30344294/211021299-522aff7d-bbed-4ee0-92a0-3f4707e0a10c.png">

The `Shared linux root directory` option under the `Advanced` config tab works fine though.

**Comment by Chez123321** [comment]
@sleeyax I gave up on it, sorry
